import React, { useState } from "react";
import { 
  Flame, Sparkles, Trophy, Calendar, CheckCircle2, ChevronRight, 
  RotateCcw, Info, Heart, Bookmark, Palette, MessageSquareText, 
  Camera, Eye, UserPlus, Share2, HelpCircle, Lock, Loader2, Award,
  PartyPopper, Undo2
} from "lucide-react";
import { UserProfile, DailyMission, DailyQuestState } from "../types";

interface DashboardProps {
  profile: UserProfile;
  missions: DailyMission[];
  onActionTrigger: (mission: DailyMission) => void;
  onRegenerateMissions: () => Promise<void>;
  loadingMissions: boolean;
  isAI: boolean;
  dailyQuest: DailyQuestState;
  streakBroken: boolean;
  previousStreak: number;
  onRestoreStreak: () => Promise<void>;
  restoringStreak: boolean;
  streakRestoreError: string | null;
}

const STREAK_RESTORE_COST = 250;

export default function QuestDashboard({
  profile,
  missions,
  onActionTrigger,
  onRegenerateMissions,
  loadingMissions,
  isAI,
  dailyQuest,
  streakBroken,
  previousStreak,
  onRestoreStreak,
  restoringStreak,
  streakRestoreError
}: DashboardProps) {
  const [showAIInfo, setShowAIInfo] = useState(false);

  // Helper to map icon names to Lucide icons
  const getMissionIcon = (category: string) => {
    switch (category) {
      case "likes": return <Heart className="h-6 w-6 text-myntra-pink fill-myntra-pink" />;
      case "wishlist": return <Bookmark className="h-6 w-6 text-myntra-orange fill-myntra-orange" />;
      case "outfit": return <Palette className="h-6 w-6 text-purple-500" />;
      case "review": return <MessageSquareText className="h-6 w-6 text-blue-500" />;
      case "upload": return <Camera className="h-6 w-6 text-emerald-500" />;
      case "explore": return <Eye className="h-6 w-6 text-cyan-500" />;
      case "follow": return <UserPlus className="h-6 w-6 text-teal-500" />;
      case "share": return <Share2 className="h-6 w-6 text-pink-500" />;
      default: return <Sparkles className="h-6 w-6 text-amber-500" />;
    }
  };

  const getDifficultyStyles = (diff: string) => {
    switch (diff) {
      case "Easy": return "bg-green-50 text-green-700 border-green-100";
      case "Medium": return "bg-amber-50 text-amber-700 border-amber-100";
      case "Hard": return "bg-rose-50 text-rose-700 border-rose-100";
      default: return "bg-gray-50 text-gray-700 border-gray-100";
    }
  };

  const completedCount = missions.filter(m => m.completed).length;
  const progressPercent = missions.length > 0 ? Math.round((completedCount / missions.length) * 100) : 0;

  // Render 30-day milestone progress
  const milestones = [7, 15, 30];

  return (
    <div id="quest-dashboard-main" className="space-y-8 animate-fade-in">
      
      {/* Top Banner - Hero Card */}
      <div className="relative bg-gradient-myntra rounded-3xl p-6 text-white overflow-hidden shadow-xl">
        <div className="absolute top-0 right-0 transform translate-x-12 -translate-y-12 opacity-15">
          <Sparkles className="w-80 h-80 text-white" />
        </div>
        
        <div className="relative z-10 grid grid-cols-1 md:grid-cols-3 gap-6 items-center">
          
          {/* Welcome & Sparks */}
          <div className="space-y-2 md:col-span-2">
            <span className="bg-white/20 backdrop-blur-md text-white text-[11px] font-bold px-3 py-1 rounded-full uppercase tracking-widest font-mono">
              Myntra Quest Season 1 🎮
            </span>
            <h1 className="text-3xl font-display font-black tracking-tight">
              Hey {profile.name.split(" ")[0]}! Welcome to Quest.
            </h1>
            <p className="text-white/90 text-xs md:text-sm max-w-lg leading-relaxed">
              Unlock personalized fashion challenges generated by our AI. Accomplish missions, build streaks, and earn <span className="font-bold text-yellow-300">Myntra Sparks</span> to redeem rewards!
            </p>
            <div className="flex items-center space-x-2 pt-2">
              <span className="text-xs bg-black/15 text-white/95 px-3 py-1 rounded-md font-mono flex items-center">
                <Info className="h-3.5 w-3.5 mr-1 text-pink-200" />
                Missions refresh daily. Complete all 3 to receive +30 Sparks Bonus!
              </span>
            </div>
          </div>

          {/* Spark Balance Display */}
          <div className="bg-white/10 backdrop-blur-md rounded-2xl p-5 border border-white/20 flex flex-col justify-center items-center text-center shadow-inner">
            <Sparkles className="h-8 w-8 text-yellow-300 fill-yellow-300 animate-bounce mb-1" />
            <span className="text-xs uppercase text-white/75 font-mono tracking-wider">Sparks Balance</span>
            <span className="text-4xl font-mono font-black text-yellow-300 mt-1">{profile.sparks}</span>
            <span className="text-[10px] text-white/90 mt-1">Upgrade level: <span className="font-bold text-pink-200">Insider Elite</span></span>
          </div>

        </div>
      </div>

      {/* Daily Streak Progress Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Daily Streak Tracker */}
        <div className="glass-card-light rounded-3xl p-6 shadow-sm lg:col-span-2 flex flex-col justify-between space-y-6">
          <div className="flex justify-between items-start">
            <div className="space-y-1">
              <h2 className="text-lg font-display font-bold text-gray-800 flex items-center">
                <Flame className="h-5.5 w-5.5 text-orange-500 fill-orange-500 mr-2 animate-pulse" />
                Your Active Daily Streak
              </h2>
              <p className="text-xs text-gray-500">Completing all 3 daily missions advances your streak. Don't skip a day!</p>
            </div>
            <div className="text-right">
              <span className="text-3xl font-mono font-black text-orange-600 block leading-none">{profile.streak}</span>
              <span className="text-[9px] text-gray-400 font-mono font-bold uppercase tracking-wider">Days Hot 🔥</span>
            </div>
          </div>

          {/* Milestone timeline progress (30 Days) */}
          <div className="space-y-4">
            <div className="flex justify-between text-xs text-gray-400 font-semibold font-mono">
              <span>Day 1</span>
              <span>Day 15</span>
              <span>Day 30 (Legend Badge)</span>
            </div>
            
            <div className="relative">
              {/* Core progress line */}
              <div className="absolute top-1/2 -translate-y-1/2 left-0 right-0 h-2 bg-gray-100 rounded-full" />
              <div 
                className="absolute top-1/2 -translate-y-1/2 left-0 h-2 bg-gradient-to-r from-orange-500 to-red-500 rounded-full transition-all duration-700"
                style={{ width: `${Math.min((profile.streakProgress / 30) * 100, 100)}%` }}
              />

              {/* Dots representing 30 steps */}
              <div className="relative z-10 flex justify-between">
                {Array.from({ length: 30 }).map((_, idx) => {
                  const dayNum = idx + 1;
                  const isCurrent = dayNum === profile.streakProgress;
                  const isCompleted = dayNum < profile.streakProgress;
                  const isMilestone = milestones.includes(dayNum);

                  return (
                    <div key={dayNum} className="relative flex flex-col items-center">
                      <div 
                        className={`h-4 w-4 rounded-full flex items-center justify-center border-2 transition-all ${
                          isCurrent 
                            ? "bg-orange-500 border-white scale-125 shadow-md ring-2 ring-orange-200" 
                            : isCompleted 
                            ? "bg-orange-400 border-white" 
                            : isMilestone 
                            ? "bg-white border-orange-300" 
                            : "bg-white border-gray-200"
                        }`}
                        title={`Day ${dayNum}`}
                      />
                      {isMilestone && (
                        <span className="absolute -top-5 text-[9px] font-mono font-bold text-orange-600">
                          {dayNum}d
                        </span>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

          {/* Milestone benefits description */}
          <div className="bg-orange-50 rounded-xl p-4 border border-orange-100 flex items-start space-x-3 text-orange-800 text-xs">
            <Trophy className="h-5 w-5 text-orange-500 shrink-0 mt-0.5" />
            <div className="space-y-1">
              <p className="font-bold">Next Milestone Reward: 30-Day Legend Cycle</p>
              <p className="text-orange-700">Reach Day 30 to claim a massive bonus of <span className="font-bold">150 Sparks</span>, unlock the <b>30-Day Legend Badge</b>, and access exclusive early sales!</p>
            </div>
          </div>

          {/* Streak Restore Banner - shown only when a streak was broken */}
          {streakBroken && (
            <div className="bg-rose-50 rounded-xl p-4 border border-rose-100 flex items-start space-x-3 text-rose-800 text-xs">
              <Undo2 className="h-5 w-5 text-rose-500 shrink-0 mt-0.5" />
              <div className="space-y-2 flex-1">
                <p className="font-bold">You lost your streak yesterday.</p>
                <p className="text-rose-700">Your previous {previousStreak}-day streak was reset to 0. Restore it now before you lose the momentum for good.</p>
                {streakRestoreError && (
                  <p className="text-rose-600 font-semibold">{streakRestoreError}</p>
                )}
                <button
                  onClick={onRestoreStreak}
                  disabled={restoringStreak || profile.sparks < STREAK_RESTORE_COST}
                  className="w-full sm:w-auto flex items-center justify-center bg-[#FF3F6C] hover:bg-[#E63960] text-white py-2 px-4 rounded-xl font-bold text-xs tracking-wider uppercase transition-all shadow-md shadow-pink-100 disabled:opacity-50 cursor-pointer"
                >
                  {restoringStreak ? (
                    <>
                      <Loader2 className="h-3.5 w-3.5 animate-spin mr-2" />
                      Restoring...
                    </>
                  ) : (
                    <>
                      Restore Streak
                      <span className="ml-2 flex items-center">
                        <Sparkles className="h-3 w-3 mr-1 fill-yellow-300 text-yellow-300" />
                        {STREAK_RESTORE_COST}
                      </span>
                    </>
                  )}
                </button>
                {profile.sparks < STREAK_RESTORE_COST && (
                  <p className="text-rose-500">You need {STREAK_RESTORE_COST - profile.sparks} more Sparks to restore.</p>
                )}
              </div>
            </div>
          )}
        </div>

        {/* AI Generator Control Center */}
        <div className="glass-card-light rounded-3xl p-6 shadow-sm flex flex-col justify-between space-y-6">
          {dailyQuest.completed ? (
            <>
              <div className="space-y-2">
                <div className="flex items-center space-x-1">
                  <span className="bg-green-50 text-green-700 text-[10px] font-mono font-bold px-2 py-0.5 rounded-full uppercase">
                    Quest Complete
                  </span>
                </div>
                <h3 className="text-lg font-display font-bold text-gray-800 flex items-center">
                  <PartyPopper className="h-5 w-5 text-myntra-pink mr-2" />
                  Daily Quest Completed!
                </h3>
                <p className="text-xs text-gray-500 leading-relaxed">
                  Come back tomorrow for new personalized missions.
                </p>
              </div>

              <button
                disabled
                className="w-full flex items-center justify-center bg-gray-100 text-gray-400 py-3.5 px-4 rounded-xl font-bold text-xs tracking-wider uppercase cursor-not-allowed"
              >
                <Lock className="h-4 w-4 mr-2" />
                Come Back Tomorrow
              </button>
            </>
          ) : (
            <>
              <div className="space-y-2">
                <div className="flex items-center space-x-1">
                  <span className="bg-pink-50 text-myntra-pink text-[10px] font-mono font-bold px-2 py-0.5 rounded-full uppercase">
                    {isAI ? "Gemini 3.5 AI Active ✨" : "Smart Fallback Active"}
                  </span>
                </div>
                <h3 className="text-lg font-display font-bold text-gray-800">Mission Customizer</h3>
                <p className="text-xs text-gray-500 leading-relaxed">
                  Not liking your missions today? Ask Gemini AI to reconstruct personalized challenges tailored to your real browsing patterns, brand follows, and category preferences.
                </p>
              </div>

              <button
                onClick={onRegenerateMissions}
                disabled={loadingMissions || dailyQuest.personalizedMissionGenerated}
                className="w-full flex items-center justify-center bg-[#FF3F6C] hover:bg-[#E63960] text-white py-3.5 px-4 rounded-xl font-bold text-xs tracking-wider uppercase transition-all shadow-lg shadow-pink-100 hover:shadow-pink-200 active:scale-98 disabled:opacity-50 disabled:shadow-none cursor-pointer disabled:cursor-not-allowed"
              >
                {loadingMissions ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin mr-2 text-pink-100" />
                    Gemini Personalizing...
                  </>
                ) : dailyQuest.personalizedMissionGenerated ? (
                  <>
                    <Lock className="h-4 w-4 mr-2" />
                    Already Personalized Today
                  </>
                ) : (
                  <>
                    <RotateCcw className="h-4 w-4 mr-2 text-pink-200" />
                    AI Personalize Missions
                  </>
                )}
              </button>

              <p className="text-[10px] text-center text-gray-400">
                {dailyQuest.personalizedMissionGenerated
                  ? "Come back tomorrow for a fresh set of AI missions."
                  : "Powered by Gemini with real-time feedback loops."}
              </p>
            </>
          )}
        </div>

      </div>

      {/* Daily Missions Progress Bar & Header */}
      <div className="space-y-4">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
          <div className="space-y-0.5">
            <h2 className="text-xl font-display font-black text-gray-800 flex items-center">
              Active Daily Quests
              <span className="ml-2 text-xs font-mono font-bold bg-pink-100 text-myntra-pink px-2.5 py-0.5 rounded-full">
                {completedCount}/3 Finished
              </span>
            </h2>
            <p className="text-xs text-gray-500">Perform the challenges below. Verification is automatic — no manual clicking needed.</p>
          </div>

          {/* Today's total completion progress bar */}
          <div className="w-full sm:w-64 space-y-1">
            <div className="flex justify-between text-xs font-mono font-bold text-gray-600">
              <span>Today's Completion</span>
              <span>{progressPercent}%</span>
            </div>
            <div className="h-3 bg-gray-100 rounded-full overflow-hidden border border-gray-200 shadow-inner">
              <div 
                className="h-full bg-gradient-myntra rounded-full transition-all duration-500"
                style={{ width: `${progressPercent}%` }}
              />
            </div>
          </div>
        </div>

        {/* 3 Active Mission Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {missions.map((mission) => {
            const progressRatio = mission.targetCount > 0 ? mission.currentCount / mission.targetCount : 0;
            const completed = mission.completed;

            return (
              <div 
                key={mission.id}
                className={`relative rounded-2xl p-6 ${
                  completed ? "glass-card-medium border-green-200 bg-green-50/10 shadow-xs" : "glass-card-light hover:border-white/100"
                } shadow-sm flex flex-col justify-between space-y-4 transition-all hover:scale-[1.02]`}
              >
                {/* Top icons & Emoji */}
                <div className="flex justify-between items-start">
                  <div className="flex items-center space-x-2">
                    <div className="p-3 bg-white/80 rounded-xl border border-white/90 shadow-xs text-xl">
                      {mission.emoji || "✨"}
                    </div>
                  </div>
                  <div className="flex flex-col items-end space-y-1">
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border uppercase ${getDifficultyStyles(mission.difficulty)}`}>
                      {mission.difficulty}
                    </span>
                    <span className="text-xs font-mono font-bold text-yellow-600 flex items-center mt-1">
                      <Sparkles className="h-3 w-3 mr-0.5 fill-yellow-500 text-yellow-500" />
                      +{mission.points} Sparks
                    </span>
                  </div>
                </div>

                {/* Title & description */}
                <div className="space-y-1">
                  <h3 className="font-display font-black text-base text-gray-800 leading-tight flex items-center">
                    <span className="mr-1.5">{mission.emoji}</span>
                    {mission.title}
                    {completed && <CheckCircle2 className="h-4 w-4 text-green-500 fill-green-50 ml-1.5 shrink-0" />}
                  </h3>
                  <p className="text-xs text-gray-500 leading-relaxed">{mission.description}</p>
                </div>

                {/* Progress tracker */}
                <div className="space-y-1.5">
                  <div className="flex justify-between text-[11px] font-mono font-semibold text-gray-500">
                    <span>Progress</span>
                    <span className={`font-bold ${completed ? "text-emerald-600 font-extrabold" : "text-gray-700"}`}>
                      {mission.currentCount}/{mission.targetCount}
                      {(completed || mission.currentCount >= mission.targetCount) ? " (Mission Complete)" : ""}
                    </span>
                  </div>
                  <div className="h-2.5 bg-gray-100 rounded-full overflow-hidden border border-gray-200 shadow-inner">
                    <div 
                      className={`h-full rounded-full transition-all duration-700 ease-out ${
                        completed ? "bg-emerald-500 shadow-sm" : "bg-gradient-myntra"
                      }`}
                      style={{ width: `${Math.min(progressRatio * 100, 100)}%` }}
                    />
                  </div>
                </div>

                {/* AI Explanation reason */}
                {mission.personalizedReason && (
                  <div className="bg-pink-50/50 rounded-xl p-3 border border-pink-100/50 text-[11px] text-pink-700 leading-relaxed italic">
                    {mission.personalizedReason}
                  </div>
                )}

                {/* Play Action button */}
                <button
                  onClick={() => onActionTrigger(mission)}
                  disabled={completed}
                  className={`w-full py-2.5 px-3 rounded-xl font-bold text-xs tracking-wider uppercase flex items-center justify-center transition-all cursor-pointer ${
                    completed 
                      ? "bg-green-50 text-green-700 border border-green-200 cursor-default font-mono" 
                      : "bg-[#FF3F6C] hover:bg-[#E63960] text-white shadow-md shadow-pink-100 hover:shadow-pink-200 active:scale-98"
                  }`}
                >
                  {completed ? (
                    "Mission Completed ✓"
                  ) : (
                    <>
                      Enter Challenge
                      <ChevronRight className="h-3.5 w-3.5 ml-1 text-white" />
                    </>
                  )}
                </button>
              </div>
            );
          })}
        </div>
      </div>

      {/* Badges / Achievements shelf */}
      <div className="glass-card-light rounded-3xl p-6 shadow-sm space-y-4">
        <h3 className="text-lg font-display font-bold text-gray-800 flex items-center">
          <Award className="h-5.5 w-5.5 text-myntra-pink mr-2" />
          Fashion Achievement Badges
        </h3>
        
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-center">
          
          <div className="p-4 border border-pink-100 bg-white/50 rounded-2xl flex flex-col items-center justify-center backdrop-blur-xs transition-transform hover:scale-105 shadow-xs">
            <div className="h-12 w-12 rounded-full bg-pink-100 text-[#FF3F6C] flex items-center justify-center mb-2 shadow-xs">
              <Sparkles className="h-6 w-6" />
            </div>
            <p className="text-xs font-bold text-gray-800">Quest Starter</p>
            <p className="text-[10px] text-gray-400 mt-1">Unlocked Day 1</p>
          </div>

          <div className={`p-4 border rounded-2xl flex flex-col items-center justify-center backdrop-blur-xs transition-transform hover:scale-105 shadow-xs ${
            profile.streak >= 7 ? "border-orange-100 bg-white/50" : "border-gray-150/40 opacity-60 bg-gray-50/20"
          }`}>
            <div className={`h-12 w-12 rounded-full flex items-center justify-center mb-2 shadow-xs ${
              profile.streak >= 7 ? "bg-orange-100 text-orange-500" : "bg-gray-200 text-gray-400"
            }`}>
              <Flame className="h-6 w-6" />
            </div>
            <p className="text-xs font-bold text-gray-800">Week Flame</p>
            <p className="text-[10px] text-gray-400 mt-1">{profile.streak >= 7 ? "Unlocked Day 7" : "Locked (Need 7d Streak)"}</p>
          </div>

          <div className={`p-4 border rounded-2xl flex flex-col items-center justify-center backdrop-blur-xs transition-transform hover:scale-105 shadow-xs ${
            profile.badges.some(b => b.id.includes("milestone-30")) ? "border-purple-100 bg-white/50" : "border-gray-150/40 opacity-60 bg-gray-50/20"
          }`}>
            <div className={`h-12 w-12 rounded-full flex items-center justify-center mb-2 shadow-xs ${
              profile.badges.some(b => b.id.includes("milestone-30")) ? "bg-purple-100 text-purple-600" : "bg-gray-200 text-gray-400"
            }`}>
              <Trophy className="h-6 w-6" />
            </div>
            <p className="text-xs font-bold text-gray-800">30-Day Legend</p>
            <p className="text-[10px] text-gray-400 mt-1">
              {profile.badges.some(b => b.id.includes("milestone-30")) ? "Unlocked!" : "Locked (Need 30d Streak)"}
            </p>
          </div>

          <div className={`p-4 border rounded-2xl flex flex-col items-center justify-center backdrop-blur-xs transition-transform hover:scale-105 shadow-xs ${
            profile.sparks >= 300 ? "border-yellow-100 bg-white/50" : "border-gray-150/40 opacity-60 bg-gray-50/20"
          }`}>
            <div className={`h-12 w-12 rounded-full flex items-center justify-center mb-2 shadow-xs ${
              profile.sparks >= 300 ? "bg-yellow-100 text-yellow-600" : "bg-gray-200 text-gray-400"
            }`}>
              <Award className="h-6 w-6" />
            </div>
            <p className="text-xs font-bold text-gray-800">Spark Millionaire</p>
            <p className="text-[10px] text-gray-400 mt-1">{profile.sparks >= 300 ? "Unlocked!" : "Locked (Need 300 Sparks)"}</p>
          </div>

        </div>
      </div>

    </div>
  );
}
